name: setup
description: Sets up a CI job
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: npm
    - run: npm ci
      shell: bash
    - uses: homebrew/actions/setup-homebrew@master
    - run: brew install --cask inkscape
      shell: bash
